### ISSUE TITLE
Library is not working

### ISSUE THREAD

**Issue by bdairy** [imaNNeoFighT/circular_bottom_navigation#15]
Used the same exact setup in the documentation.. 

![image](https://user-images.githubusercontent.com/10797121/67490961-cd2a7480-f67c-11e9-88c8-8731a18977ec.png)

Had this error 

![image](https://user-images.githubusercontent.com/10797121/67491007-dca9bd80-f67c-11e9-8704-bc086ec27cb6.png)

Added the controller... the index of the call back always returns 0.... ???

**Comment by raegartargarian** [comment]
this is my problem too, any suggestions?

**Comment by tedchuang** [comment]
I can't see your code but i think you're using a CircularBottomNavigation in each of your subsequent widgets called up by the bottom nav. If not, just ignore this post LOL

Ideally, you would set up a home page scaffold with a container widget on the top and the CircularBottomNavigation at the bottom. Each tap of the bottom navigation will change the said container widget only. The same bottom nav bar is visible throughout the tab choices, unless you push to another page route.

Don't include another instance of the CircularBottomNavigation in the container widgets. Ideally you should only have call the CircularBottomNavigation once in your entire app.

**Comment by harshbarnwal** [comment]
@bdairy I have same problem, it arises because you are not providing `CircularBottomNavigationController`.
Just declare and initialize CircularBottomNavigationController with the index of item you want to open application like...
`int selectedPos = 0;
var _navigationController = new CircularBottomNavigationController(selectedPos);`
pass this controller to CircularBottomNavigation and in selectedCallback method save do like
`selectedCallback: (int selectedPos) {
              this.selectedPos = selectedPos;
            }`
adding these resolved my problem.

**Comment by benyaminbeyzaie** [comment]
Closing this issue cause it is not active for years, If the issue persists please open another one and describe with details. Adding your code as an attachments maybe helpful! Thanks!
